### ISSUE TITLE
serializeIcon returns wrong key

### ISSUE THREAD

**Issue by QuentinG3** [Ahmadre/FlutterIconPicker#23]
Hi,

I am using flutter_iconpicker version 3.0.1+2. 
When using the method serializeIcon using the material pack I am not getting the correct key as output.
If using **serializeIcon** and **deserializeIcon** in chain I get the same IconData. However if I only use **serializeIcon** and check the store result in data base I do not get the correct Key.

For instance: 

Example (**serializeIcon**)
- Input: Icons.location_on
- Output: {"key": "read_more_outlined", "pack": "material"}

Thank you !

**Comment by Ahmadre** [comment]
This is related to constant changes from Flutter MaterialIcons. They changed the codePoints and that leads to inconvinience in other packsges.

As you already mention if you serialize and deserialze everything is fine, therefore because the Flutter Team always changed the codePoints our serialization is handling this. So don't worry if you see other keys in your db. 

But I'll update the MaterialIcon Map so the keys are correct in the DB.

I hope this Flutter Team will not change the codePoints again, otherwise we'll have to find another way rather then mapping...

**Comment by Ahmadre** [comment]
I also know where I cause issue is. I'll fix this now

**Comment by Ahmadre** [comment]
Fixed with v. 3.0.2

Please update and thanks for using my package 💙
