### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by CripyIce** [Ahmadre/FlutterIconPicker#42]
After upgrading to Flutter 2.10.2, there is a new error regards to an icon being removed.
```
    ../../.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.2/lib/IconPicker/Packs/Material.dart:4894:31: Error: Member not found: 'pie_chart_outlined'.
      'pie_chart_outlined': Icons.pie_chart_outlined,
                                  ^^^^^^^^^^^^^^^^^^
```

**Comment by potay** [comment]
+1

**Comment by nicolashasenkopf** [comment]
+1

**Comment by ccfiel** [comment]
same here

**Comment by corioste** [comment]
added fixed https://github.com/Ahmadre/FlutterIconPicker/pull/43

**Comment by ccfiel** [comment]
@Ahmadre can you please merge the main branch. thanks!

**Comment by RohanPatil1** [comment]
Any Update on this??

**Comment by ameenvga** [comment]
any update?

**Comment by anderson-oki** [comment]
Maybe we should find a way to remove the dependancy of the `Packs`. They have been introducing breaking changes several times in Material and FontAwesome.

**Comment by hesty98** [comment]
When will this be published?

**Comment by Apfelwurm** [comment]
am i wrong or wouldn't be the fix to just change it from 'pie_chart_outlined' to 'pie_chart_outline' due to  https://github.com/flutter/flutter/pull/96115 ? and also it would be really cool if this would get into a new version

**Comment by Apfelwurm** [comment]
cause it seems @Ahmadre had no time, for all that come across this issue, you can temporary use the git provider in your pubspec like this to obtain the fixed version:
``` 
dependencies:
  flutter_iconpicker:
    git:
      url: https://github.com/Ahmadre/FlutterIconPicker.git
      ref: master
``` 
keep in mind that this is not a change you should make forever, since there will maybe be experimental changes on the master here before a future release. You could also set the ref to ```a318bbe4ac4b318549234cf7354bdcd9faf88b16``` which referes to the current fixing commit, but that is also nothing you should have permanently, since it wont get updated if there are new versions or commits

**Comment by Ahmadre** [comment]
New Release is up guys [![Generic badge](https://img.shields.io/badge/platform-android%20|%20ios%20|%20web%20|%20desktop-blue.svg)](https://pub.dev/packages/flutter_iconpicker)
