### ISSUE TITLE
Opening really slow

### ISSUE THREAD

**Issue by frederikw03** [Ahmadre/FlutterIconPicker#7]
When i click Open IconPicker it takes about 3 seconds before it opens. is it possible to remove some icons to make it open faster? i don't need all the icons. is it also possible to add icons myself as the developer?

**Comment by Ahmadre** [comment]
@frederikw03 Thanks you for your issue!

Like you saw i  previous issues, it was tried to fix this, but best solutio  would be infinite scrolling. If you like you can contribute to this project. All contributions are welcome :).

Actually I'm a bit busy.

Best regards and thanks for using this package 💪🏼

**Comment by leonardarnold** [comment]
Hi Rebar, thanks for the package!

I am using it for a prototype and stumbled on the same issue.
The delay is because the list is a `SingleChildScrollView` with a `Wrap` as a child. With so many items it's heavy. I could fix it by replacing it with a `GridView.builder`. The performance now feels like 1000 times better.

I didn't do a PullRequest because this breaks your adaptive layout a bit and needs some logic for responsiveness.

I forked it here: https://github.com/leonardarnold/FlutterIconPicker.

Tell me if you need more code to fix this.

Stay safe! :)


![Screenshot 2020-06-17 at 19 07 36](https://user-images.githubusercontent.com/2777184/84927926-dc5ba800-b0cd-11ea-8347-99369c4a9a2d.png)
![Screenshot 2020-06-17 at 19 01 55](https://user-images.githubusercontent.com/2777184/84927935-df569880-b0cd-11ea-8adf-cbe369df4764.png)

**Comment by Ahmadre** [comment]
@leonardarnold Thank you soo much for your work :)!! Really appreciate it!

Don't worry I got a responsive solution for a responsive GridView. I did that earlier for a customer project. I'll have a look and improve it :)

Thank you, thank you, thank you!

**Comment by NiamhG** [comment]
Hey, just wondering if you had a timescale for adding in your fix @Ahmadre ? Not wanting to rush, just curious.

Love the project btw, was exactly what I needed :)

**Comment by Ahmadre** [comment]
Hey guys, sorry for the long delay. I will do that now and let you know it an update was uploaded :)

**Comment by Ahmadre** [comment]
Alright guys: new Update is up: [![Version](https://img.shields.io/badge/pub-v2.1.1-blue)](https://pub.dev/packages/flutter_iconpicker)

**Comment by NiamhG** [comment]
Works beautifully, thanks again @Ahmadre !

**Comment by frederik0312** [comment]
Is it possible to get the icons real color? Or how could i do this?
Thanks i really like the update

**Comment by Ahmadre** [comment]
@frederik0312 The iconColor is reacting to Theme changes so it is also compatible with darkTheme for example.

But you can control the iconColor on your own if you like.
Have a look into the API-Reference: https://github.com/Ahmadre/FlutterIconPicker#api-reference

**Comment by frederik0312** [comment]
Thanks for the answer, but i meant more like the icons true color. Like blue Facebook, yellow snapchat , and some multicolored like Instagram?

**Comment by Ahmadre** [comment]
@frederik0312 Ah I know what you mean. Actually that would be a good question for the owners of the FontAwesome Package.

Or would you expect this to be in this package?

Let me know and maybe we can work on a practical solution :)

**Comment by frederikw03** [comment]
Honestly i would LOVE it to be in this package. It would be awesome to have it all together

________________________________
