### ISSUE TITLE
icons are not appearing at all.

### ISSUE THREAD

**Issue by ankarastrix** [Ahmadre/FlutterIconPicker#88]
I tried your example, but the icons are not appearing at all. I was using an older build, and everything was fine, but 4.0.1 does not work for search. Please clarify.

**Comment by Ahmadre** [comment]
> I tried your example, but the icons are not appearing at all. I was using an older build, and everything was fine, but 4.0.1 does not work for search. Please clarify.

Thank you for your issue.

This package is using code generation to minimize your apps size to be as small as possible.

You have to generate the icon packs you want on your own (even in example!) This is because generated code is not meant to be pushed into repositories.

Please read in the README the section: "Before getting started (important)".

I wrote it multiple times in the README so that people see that you have to generate your packs or icons before starting your apps.

**Comment by Ahmadre** [comment]
I'll close this issue due to inactivity. Plesae re-open anytime, if you still got issues. Please read the README carefully.
