### ISSUE TITLE
not working with cloudflare pages (on Flutter master channel)

### ISSUE THREAD

**Issue by veluloganathan** [Ahmadre/FlutterIconPicker#90]
Hi Folks, 

`if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && ls && flutter/bin/flutter doctor && flutter/bin/flutter clean && flutter/bin/flutter config --enable-web && flutter/bin/flutter pub get && flutter/bin/flutter pub run flutter_iconpicker:generate_packs --packs material,cupertino && flutter/bin/flutter build web --release --no-tree-shake-icons`

Above is my build command for deploying app in cloudflare pages. I don't see icons in the picker. Can anyone help me?

**Comment by veluloganathan** [comment]
<img width="731" alt="Screenshot 2024-12-17 at 7 08 39 PM" src="https://github.com/user-attachments/assets/7aa6fe95-df06-408d-b3bd-966b750eb078" />

Generated successfully but not showing up in the picker. 

`Flutter (Channel master, 3.28.0-1.0.pre.159, on Ubuntu 22.04.4 LTS 4.4.0, locale en_US)`

**Comment by veluloganathan** [comment]
Working fine with Flutter 3.24.5.

**Comment by Ahmadre** [comment]
> <img alt="Screenshot 2024-12-17 at 7 08 39 PM" width="731" src="https://private-user-images.githubusercontent.com/7304919/396518868-7aa6fe95-df06-408d-b3bd-966b750eb078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDg4NzUsIm5iZiI6MTczNTE0ODU3NSwicGF0aCI6Ii83MzA0OTE5LzM5NjUxODg2OC03YWE2ZmU5NS1kZjA2LTQwOGQtYjNiZC05NjZiNzUwZWIwNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMTc0MjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGI4MTliY2U1Y2FhZThhODRkMzY4Nzc5MTYxNGVjZDYxOWVlOWNhYTgwOWRjNGNkNjFlYWI0MmU4ODU0MDM1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.XSPDGp_5gvxBJq8K-_COXe2dF7D2RBNNuvXXEFB0-3A">
> Generated successfully but not showing up in the picker.
> 
> `Flutter (Channel master, 3.28.0-1.0.pre.159, on Ubuntu 22.04.4 LTS 4.4.0, locale en_US)`

Thank you so much for your issue! 

We always test again `stable` branch. If migration to flutter master SDK is not breaking the current stable sdk, then I will create a PR and re-produce this on my machine.

If the latest changes with master branch are not working with Flutter stable, I cannot mirgate to master channel.

I will let you know here :)

**Comment by Ahmadre** [comment]
I tested this on my clean environment on my:
- `macOS Sequoia 15.2` machine with
- `Google Chrome Client Version 131.0.6778.205`

## Stable (3.27.1):
<img width="857" alt="stable_3 27 1" src="https://github.com/user-attachments/assets/92d9dc37-813c-4191-b048-8cb7d997fb9b" />

## Master (3.28.0-2.0.pre.38577 - latest master on 25.'th of december 2024):
<img width="811" alt="master_ 3 28 0-2 0 pre 38577" src="https://github.com/user-attachments/assets/460bf04e-60ff-4712-aafd-c1d8dc88176f" />

On both Flutter SDK's I downloaded the SDK Tools freshly and I couldn't reproduce your issue.

My generate command was:

> dart run flutter_iconpicker:generate_packs --packs material,cupertino

Please check everythring on your cloudflage pages continous integration commands and try using `dart run ...` instead of `flutter pub ...`. Maybe you didn't get the update from the Flutter team but all commands with `flutter pub ...` are deprecated.
